name: pkgcruft

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        fetch-depth: 0
    - name: Run pkgcruft
      uses: pkgcraft/pkgcruft-action@main
